name: create-release

env:
  VERSION: "v1.0.1" # по-хорошему надо брать из названия ветки: ${{ github.ref }}

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: test-print-env
        run: |
          echo "version: ${{ env.VERSION }}"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: |
            Created new package version
          draft: false
          prerelease: false
